import Head from "next/head";
import { type NextPage } from "next";
import { useId, useState } from "react";
import { useAccount, useContractRead, useContractWrite } from "wagmi";
import { abi, contractAddress } from "~/contracts/NFT";
import NoSSR from "react-no-ssr";
import NFTImage from "~/components/nftImage";
import Link from "next/link";

import { MdCollectionsBookmark } from "react-icons/md";
import { AiOutlineAppstoreAdd } from "react-icons/ai";
import { FaBullseye } from "react-icons/fa";
import EnsureWallet from "~/components/ensureWallet";

const Home: NextPage = () => {
  const account = useAccount();

  return (
    <>
      <Head>
        <title>Mothora NFT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-start">
        <div className="mt-4 flex w-full flex-col items-start gap-12 px-4">
          <p className="text-4xl font-extrabold tracking-tight text-white">
            Welcome to the Mothora NFT Demo
          </p>
          <NoSSR>
            {account.status === "connected" ? (
              <div className="flex w-full flex-col gap-4">
                <Link href="/my-nfts">
                  <button className="btn-primary btn flex w-full gap-2">
                    <MdCollectionsBookmark size={24} />
                    My NFTs
                  </button>
                </Link>
                <Link href="/mint">
                  <button className="btn-primary btn flex w-full gap-2">
                    <AiOutlineAppstoreAdd size={24} />
                    Mint NFT
                  </button>
                </Link>
                <Link href="/get-by-id">
                  <button className="btn-primary btn flex w-full gap-2">
                    <FaBullseye size={24} />
                    Get NFT by Id
                  </button>
                </Link>
              </div>
            ) : (
              <EnsureWallet />
            )}
          </NoSSR>
        </div>
      </main>
    </>
  );
};

export default Home;
